#!/bin/sh

# ====================================
# Initialization
# ====================================

# Inspired by "probe" in oe-init-build-env
if [ -n "$BASH_SOURCE" ]; then
    this_script=$BASH_SOURCE
elif [ -n "$ZSH_NAME" ]; then
    this_script=$0
else
    this_script="$(pwd)/setup-environment"
fi

script_dir=$(dirname "$this_script")
script_dir=$(readlink -f "$script_dir")
build_dir=${script_dir}/build

target=""
stage=""

targets=(
    "raspberrypi"
    "qemu"
    "intel"
)

stages=(
  "prod"
  "dev"
)

# ====================================
# Read target input
# ====================================
for i in ${targets[@]}
do
    if [[ $i == $1 ]]
    then
        target=$1
        break
    fi
done

if [ -z "${target}" ]; then
    echo "Sorry, it does not seem that *$1* is a valid target"
    echo ""
    echo "Usage: setup-environment <target> <stage>"
    echo ""

    printf "Supported targets are:\n"
    printf '%s\n' "${targets[@]}"
    return 1
fi

# ====================================
# Read stage input
# ====================================
for i in ${stages[@]}
do
    if [[ $i == $2 ]]
    then
        stage=$2
        break
    fi
done

if [ -z "${stage}" ]; then
    echo "Sorry, it does not seem that *$2* is a valid stage"
    echo ""
    echo "Usage: setup-environment <target> <stage>"
    echo ""

    printf "Supported stages are:\n"
    printf '%s\n' "${stages[@]}"
    return 1
fi

# ====================================
# Init poky build
# ====================================
. ${script_dir}/sources/poky/oe-init-build-env ${build_dir}

# ====================================
# Copy target specific configs
# ====================================

# Target configuration
cat ${script_dir}/${target}/templates/${stage}/local.conf > ${build_dir}/conf/local.conf
# Layer config
cp ${script_dir}/${target}/templates/${stage}/bblayers.conf ${build_dir}/conf/bblayers.conf

# ====================================
# Copy shared configs
# ====================================

cat ${script_dir}/templates/${stage}/*.local.conf.append >> ${build_dir}/conf/local.conf