#!/bin/sh

# Inspired by "probe" in oe-init-build-env
if [ -n "$BASH_SOURCE" ]; then
    this_script=$BASH_SOURCE
elif [ -n "$ZSH_NAME" ]; then
    this_script=$0
else
    this_script="$(pwd)/setup-environment"
fi

script_dir=$(dirname "$this_script")
script_dir=$(readlink -f "$script_dir")
build_dir=${script_dir}/build

target=""

targets=(
    "raspberrypi"
    "qemu"
)

for i in ${targets[@]}
do
    if [[ $i == $1 ]]
    then
        target=$1
        break
    fi
done

if [ -z "${target}" ]; then
    echo "Sorry, it does not seem that *$1* is a valid target"
    echo ""

    printf "Supported targets are:\n"
    printf '%s\n' "${targets[@]}"
    return 1
fi

# Remove existing config (Needed for incremental sync and build)
rm -f ${build_dir}/conf/local.conf

# Init poky build
. ${script_dir}/sources/poky/oe-init-build-env ${build_dir}

# Common entries Project
cat ${script_dir}/templates/*.local.conf.append >> ${build_dir}/conf/local.conf

# Board specific entries
target_templates=${script_dir}/${target}/templates
cp ${target_templates}/bblayers.conf.sample ${build_dir}/conf/bblayers.conf
cat ${target_templates}/local.conf.append >> ${build_dir}/conf/local.conf